import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { PLATFORM_RULES, headingSlug } from '../packages/saas-platform-nest/dist/platform/index.js';

// `docs/reference/options.md` is generated from the rule table, and every rule's
// boot error ends in a link to one of its headings.
//
// Two things can go wrong, and they fail differently on purpose. The page can
// fall behind the rules — a rule added, renamed or reworded, and a reader sent
// to a page describing the old one. And a link can point at a heading that does
// not exist, which does not 404: GitHub silently lands the reader at the top of
// the page, so the link looks like it worked.
//
// `tests/docs-links-resolve.test.js` catches the second kind for links written
// in markdown. These are written in TypeScript, so they need their own.

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));
const PAGE = new URL('../docs/reference/options.md', import.meta.url);

const page = readFileSync(PAGE, 'utf8');

/** GitHub's slug, applied to every heading in the page. */
const anchorsInPage = new Set([...page.matchAll(/^#{1,6} (.+)$/gm)].map((m) => headingSlug(m[1])));

describe('the options reference is generated, not maintained', () => {
    test('the committed page is what the generator produces', () => {
        const regenerated = execFileSync(process.execPath, ['scripts/gen-options-reference.mjs'], {
            cwd: REPO_ROOT,
            encoding: 'utf8',
        });
        assert.equal(
            page,
            regenerated,
            'docs/reference/options.md is out of date — run: node scripts/gen-options-reference.mjs --write',
        );
    });

    test('it says it is generated, at the top where an editor would see it', () => {
        assert.match(page.split('\n')[0], /Generated by scripts\/gen-options-reference\.mjs/);
    });
});

describe('every rule links to a heading that exists', () => {
    for (const rule of PLATFORM_RULES) {
        test(`${rule.id} resolves`, () => {
            const [, anchor] = rule.docs.split('#');
            assert.ok(anchor, `${rule.id} has no anchor at all`);
            assert.ok(
                anchorsInPage.has(anchor),
                `${rule.id} links to #${anchor}, which is not a heading in options.md`,
            );
        });
    }

    test('the slug is the one GitHub uses', () => {
        // Pinned with literals rather than derived, because the point of the
        // cases above is that the anchor and the heading agree — and they would
        // agree just as happily on a slug GitHub does not produce. This is the
        // one place the algorithm itself is stated.
        assert.equal(headingSlug('core.adapters-bound'), 'coreadapters-bound');
        assert.equal(headingSlug('Reading a failed boot'), 'reading-a-failed-boot');
        assert.equal(headingSlug('  Mixed Case & Punctuation!  '), 'mixed-case--punctuation');
    });

    test('there are rules to check at all', () => {
        // Without this the loop above is vacuously green on an empty table.
        assert.ok(PLATFORM_RULES.length >= 15, `only ${PLATFORM_RULES.length} rules`);
    });
});
