// Q.4 — Codegen drift gate for the generated TypeScript types.
//
// Regenerates the TS files from the JSON schemas and compares them against the
// committed state. Drift = PR block. Anyone who changes a schema MUST also run
// `pnpm gen:types` and commit the new snapshots — that makes every schema cut
// visible in the PR diff.

// @requirement SC-SPEC-001 — A trial commits to nothing, so a plan change during one takes effect at once
// @requirement SC-COMP-008 — An implementation offers only what it can actually answer

import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { mkdtempSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    compileSchemaWithDefs,
    HEADER,
    SCHEMA_DIR,
    schemasToGenerate,
} from '../scripts/codegen-helper.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const GEN_DIR = resolve(HERE, '../src/generated');

// Off the schema directory, not a list — the same source the generator reads.
// A list here would have to be kept in step with the generator's by hand, and
// the schema somebody forgets to add is generated by one and checked by
// neither, which is a drift gate that is green because it looked nowhere.
const SCHEMAS = schemasToGenerate();

async function regenerate(schemaFile, rootName) {
    const raw = await readFile(join(SCHEMA_DIR, schemaFile), 'utf8');
    const schema = JSON.parse(raw);
    const body = await compileSchemaWithDefs(schema, rootName);
    const banner = HEADER.replace('{{schemaFile}}', schemaFile);
    return banner + '\n' + body;
}

describe('Q.4 Codegen drift gate', () => {
    // The cases below are generated from the list, so an empty list is a suite
    // that passes by looking nowhere. Asked as a pairing rather than a count:
    // it also catches the generated file whose schema was deleted underneath
    // it, which the loop can never reach.
    test('every schema has a generated file, and every generated file a schema', () => {
        const generated = readdirSync(GEN_DIR)
            .filter((name) => name.endsWith('.gen.ts'))
            .sort();
        const expected = SCHEMAS.map(({ file }) => file.replace('.schema.json', '.gen.ts')).sort();
        assert.ok(
            expected.length > 0,
            'no schemas found — the schema directory or the `.schema.json` suffix moved',
        );
        assert.deepEqual(generated, expected);
    });

    test('a schema with no title is refused rather than generated as undefined', () => {
        // The root type name is the schema's `title`, so a schema without one
        // would otherwise reach the compiler as `undefined` and fail there,
        // naming the compiler rather than the file that has to be fixed.
        const dir = mkdtempSync(join(tmpdir(), 'saasicat-schema-'));
        writeFileSync(join(dir, 'untitled.schema.json'), JSON.stringify({ type: 'object' }));
        assert.throws(() => schemasToGenerate(dir), /untitled\.schema\.json has no `title`/);
        // And the counter-check, so the refusal is about the title and not
        // about the directory being a fixture.
        writeFileSync(
            join(dir, 'untitled.schema.json'),
            JSON.stringify({ title: 'Untitled', type: 'object' }),
        );
        assert.deepEqual(schemasToGenerate(dir), [
            { file: 'untitled.schema.json', rootName: 'Untitled' },
        ]);
        rmSync(dir, { recursive: true, force: true });
    });

    for (const { file, rootName } of SCHEMAS) {
        const genFile = file.replace('.schema.json', '.gen.ts');
        test(`${genFile} is in sync with ${file}`, async () => {
            const fresh = await regenerate(file, rootName);
            const committed = await readFile(join(GEN_DIR, genFile), 'utf8');
            if (fresh !== committed) {
                throw new Error(
                    `${genFile} is out of date — the schema and the committed snapshot have drifted.\n` +
                        `Fix: run \`pnpm --filter @saasicat/core gen:types\` and commit the ` +
                        `diff in src/generated/${genFile}.\n` +
                        `Never hand-edit the generated file: the next regeneration discards it.`,
                );
            }
            assert.equal(fresh, committed);
        });
    }
});
