// DI-Tokens für die Promo-Module-Adapter.
// Konsumenten injizieren ihre Adapter-Implementations über diese Symbol-Tokens
// in `PromoCodesModule.forRoot({...})`.

export const PROMO_CODE_REPOSITORY_TOKEN = Symbol('PROMO_CODE_REPOSITORY');
export const PROMO_CODE_REDEMPTION_REPOSITORY_TOKEN = Symbol('PROMO_CODE_REDEMPTION_REPOSITORY');
export const PROMO_CODE_VALIDATION_LOG_REPOSITORY_TOKEN = Symbol(
    'PROMO_CODE_VALIDATION_LOG_REPOSITORY',
);
export const PROMO_FIRST_TIME_CUSTOMER_CHECK_TOKEN = Symbol('PROMO_FIRST_TIME_CUSTOMER_CHECK');
export const PROMO_SUBSCRIPTION_LOOKUP_TOKEN = Symbol('PROMO_SUBSCRIPTION_LOOKUP');
export const PROMO_REVENUE_DEDUCTION_AGGREGATOR_TOKEN = Symbol(
    'PROMO_REVENUE_DEDUCTION_AGGREGATOR',
);
export const PROMO_TRANSACTION_RUNNER_TOKEN = Symbol('PROMO_TRANSACTION_RUNNER');
export const PROMO_SERVICE_CONFIG_TOKEN = Symbol('PROMO_SERVICE_CONFIG');
